import time
from Process import Process

my_life = Process.create_first_process()
time.sleep(1)
my_life.act('Первое сообщение в первом процессе')
time.sleep(1)
first_person = my_life.act('SPLIT', official=True)
time.sleep(1)
first_person.act('Первое сообщение во втором процессе')
time.sleep(1)
second_person = my_life.act('SPLIT', official=True)
time.sleep(1)
second_person.act('Первое сообщение в третьем процессе')
time.sleep(1)
second_person.act(f'CROSS {first_person.get_identifier()[0]}', official=True)
time.sleep(1)
my_life.act('Второе сообщение в первом процессе')
time.sleep(1)
first_person.act('Второе сообщение во втором процессе')
time.sleep(1)
second_person.act('Второе сообщение в третьем процессе')
time.sleep(1)

debt1 = first_person.act('SPLIT', official=True)
time.sleep(1)
debt1.act('Первое сообщение в четвёртом процессе')
time.sleep(1)

debt2 = second_person.act('SPLIT', official=True)
time.sleep(1)
debt2.act('Первое сообщение в пятом процессе')
time.sleep(1)

debt1.act('Второе сообщение в четвёртом процессе')
time.sleep(1)
debt2.act('Второе сообщение в пятом процессе')
time.sleep(1)
debt1.act('Третье сообщение в четвёртом процессе')
time.sleep(1)
debt2.act('Третье сообщение в пятом процессе')

time.sleep(1)
my_life.act('Третье сообщение в первом процессе')
time.sleep(1)
first_person.act('Третье сообщение во втором процессе')
time.sleep(1)
second_person.act('Третье сообщение в третьем процессе')


print(my_life)
print(first_person)
print(second_person)
