import time
from Process import Process

my_life = Process.create_first_process()
time.sleep(1)
my_life.act('Первое сообщение в первом процессе')
time.sleep(1)
first_person = my_life.act('SPLIT', official=True)
time.sleep(1)
first_person.act('Первое сообщение во втором процессе')
time.sleep(1)
second_person = my_life.act('SPLIT', official=True)
time.sleep(1)
second_person.act('Первое сообщение в третьем процессе')
time.sleep(1)
second_person.act(f'CROSS {first_person._me}', official=True)
time.sleep(1)
my_life.act('Второе сообщение в первом процессе')
time.sleep(1)
first_person.act('Второе сообщение во втором процессе')
time.sleep(1)
second_person.act('Второе сообщение в третьем процессе')
time.sleep(1)
debt1 = first_person.act('SPLIT', official=True)
time.sleep(1)
debt1.act('Первое сообщение в четвёртом процессе')
print(my_life)
print(first_person)
print(second_person)
